### ISSUE TITLE
Change in behaviour of LDES-extractor

### ISSUE THREAD

**Issue by woutslabbinck** [TREEcg/LDES-Extractor#1]
* Change Extractor to allow default values for `startDate` and `endDate` (see README.md)
* add optional argument to IExtractorOptions: **versionIdentifier** which results in following functionality: the extraction will only contain members with this Version Identifier

**Comment by lars-vc** [comment]
What use would default values for start- and endDate have? Because if you put new Date() as default value for both, nothing will be returned.
